### ISSUE TITLE
Error: type mismatch during compilation of raw_data_manipulation and reconstruction

### ISSUE THREAD

**Issue by heucheld** [Vindaar/TimepixAnalysis#53]
Dear all, 

after the pull of the latest pushed fix to the master (commit: f71b434) and the successful installation of the sub-modules, I get the same error in the compilation of both, raw_data_manipulation and reconstruction: 

..........................
/afs/desy.de/user/h/heucheld/.nimble/pkgs2/ginger-0.5.2-24ee12888afd1fbc44cf1f9c575e9cdb1263702d/ginger.nim(3393, 24) Warning: Vega backend does not exist. [User]
.............
/afs/desy.de/user/h/heucheld/software/TimepixAnalysis/Analysis/ingrid/private/cut_utils.nim(60, 25) Error: type mismatch
Expression: innerJoin(dfs, by = "eventNumber")
  [1] dfs: seq[DataTable[column.Column]]
  [2] by = "eventNumber": by: string

Expected one of (first mismatch at [position]):
[1] proc innerJoin[C: ColumnLike](df1, df2: DataTable[C]; by: string): DataTable[C]

The error was not apparent in commit: 310c0b4. Can you think of a fast fix? Im trying to compile it on the DESY NAF with CentOS7 and within the standard NAF environment :) @Vindaar 

Cheers,
Daniel

**Comment by Vindaar** [comment]
The issue is due to an updated dependency of the `datamancer` library. Installing the latest `datamancer` (`v0.3.17`) :

```sh
nimble install datamancer
```

should be enough to fix it. Let me know if that works.

**Comment by heucheld** [comment]
Thanks for the super quick reply!

Works very well now with the updated datamancer library.
