### ISSUE TITLE
Error: undeclared identifier: 'theme_scale' while compiling /karaPlot/plotData.nim

### ISSUE THREAD

**Issue by heucheld** [Vindaar/TimepixAnalysis#54]
Dear all,

after the last push to the master (commit 64a6928 ), I was trying to recompile plotData.nim in TimepixAnalysis/Plotting/karaPlot/ am facing an undeclared identifier error:

------
/afs/desy.de/user/h/heucheld/software/TimepixAnalysis/Plotting/karaPlot/plotData.nim(1023, 11) Error: undeclared identifier: 'theme_scale'
candidates (edit distance, scope distance); see '--spellSuggest': 
 (4, 9): 'DateScale'
 (4, 9): 'theme_latex'
 (4, 9): 'theme_opaque'
 ------

The error was not apparent in commit: https://github.com/Vindaar/TimepixAnalysis/commit/310c0b4ae423b60e144412af3428f2c3569a4f0f. 

I have investigated a bit and it seems the commit 4b6723d is related to the problem, which introduced 'theme_scale' (unfortunately I don't know via which package).

Probably Im missing a specific package (update) or something in my environment is outdated? Can you think of a fast fix? Again Im trying to compile it on the DESY NAF with CentOS7 within the standard NAF environment and nimble installed all the helper packages, etc. before according to the main README. Everything else (e.g. in the Analysis) seems to work :).

Thanks for your help in advance and cheers,
Daniel

**Comment by Vindaar** [comment]
Whoops, I got ahead of myself. It's a change in my local `ggplotnim` that I haven't pushed yet. Give me a few minutes.

**Comment by Vindaar** [comment]
Related PR:
https://github.com/Vindaar/ggplotnim/pull/175

**Comment by Vindaar** [comment]
Ok, merged the above and tagged a new version. 

```
nimble install ggplotnim
```

should make it work (should install `v0.6.3`).

**Comment by heucheld** [comment]
I confirm: with ggplotnim v.0.6.3 it compiles successfully and works well! Thanks a lot!
